<?php

namespace AppBundle\Repository;

/**
 * TwitterStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
