parameters:

services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    query_service:
      class: AppBundle\Services\QueryService
      arguments: ["@service_container"]

    role_service:
      class: AppBundle\Services\RoleService
      arguments: ["@service_container"]

    twitter_functions:
      class: AppBundle\Services\TwitterFunctions
      arguments: ['%twitter_api_key%', '%twitter_api_secret%','%twitter_api_access_token%','twitter_api_token_secret','%twitter_redirect_uri%', '@router', '@session']